[tool.poetry]
name = "hw4"
version = "0.1.0"
description = ""
authors = ["AndrewUAV"]
packages = [{include = "hw4"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"